version: "3.9"

services:
  dev:
    build:
      context: ..
      dockerfile: backend/Dockerfile.dev
    volumes:
      - ../.:/app                # Mount your local code
    command: tail -f /dev/null # Keep container alive
    container_name: app_dev
    tty: true
    working_dir: /app

  prod:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: app_prod
    ports:
      - "8080:8080"
